### ISSUE TITLE
missing xcolor.desktop file after installing with cargo

### ISSUE THREAD

**Issue by freddii** [Soft/xcolor#18]
i installed xcolor on debian with:
cargo install xcolor

But after that i got no starter in my menu.

Is there a better solution to install it?

I found the starter in the source code, but it was not installed.

https://github.com/Soft/xcolor/blob/master/extra/xcolor.desktop

**Comment by Soft** [comment]
As far as I know `cargo install` can only be used to install application binaries, it cannot install arbitrary files. This is mentioned in the readme:

>Installing xcolor with cargo will not install its manual page or desktop file. To also install these additional files, invoke make install in the project directory. By default, the install script will place the files under /usr/local/ hierarchy.

To fully install xcolor including its man page, icon, and desktop file invoke `make install` in the project directory. Note that by default this requires superuser privileges as `make` will copy the files under `/usr/local` directory.

**Comment by freddii** [comment]
worked. thanks a lot.
