### ISSUE TITLE
[feature request] notice with rgb value

### ISSUE THREAD

**Issue by freddii** [Soft/xcolor#20]
It would be handy to display the rgb value as a notification, when its in clipboard.

Maybe like this:

notify-send "XColor" --icon=xcolor "$(echo -e "RGB value\n#65c9ff\ncopied to clipboard.")"

**Comment by acheronfail** [comment]
If I'm not mistaken this should be easy enough to script yourself?

Would something like this not work for you?

```bash
get_color() {
  picked=$(xcolor)
  notify-send "xcolor" "'$picked' was copied to the clipboard"
```

**Comment by freddii** [comment]
yes:
get_color() {
  picked=$(xcolor)
  notify-send --icon=xcolor "xcolor" "'$picked' was copied to the clipboard"
}
did the trick. thanks!
