### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Barbarossa93** [Soft/xcolor#21]
Hi there, Thanks for this wonderful software!

I was wondering if you had plans for a new release soon? The last release was over 3 years ago and it seems that there has been some major improvements since then.

I went to install `xcolor` on the AUR and realized that not all of the settings documented in the README were available

**Comment by djmattyg007** [comment]
On the subject of the AUR release, I noticed that the project's LICENSE file was missing. It's supposed to be stored in `/usr/share/licenses/${pkgname}` on account of this software being MIT-licensed.

**Comment by Barbarossa93** [comment]
Looks like there's a new release! Thanks so much @Soft  :)
